http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  agencia:
    host: 52.87.222.123
    paths: ['/agencia']
    methods: ["GET","POST","PUT","DELETE","OPTIONS"]
  serviceType:
    host: 52.87.222.123
    paths: ['/serviceType']
    methods: ["GET","POST","PUT","DELETE","OPTIONS"]
  serviceAgency:
    host: 52.87.222.123
    paths: ['/serviceAgency']
    methods: ["GET","POST","PUT","DELETE","OPTIONS"]
  reporte:
    host: 52.87.222.123
    paths: ['/reporte','/reporte/*']
  users:
    host: 52.87.222.123
    paths: ['/users']
    methods: ["GET","POST","PUT","DELETE","OPTIONS"]
  ingresar:
    host: 52.87.222.123
    paths: ['/ingresar']
    methods: ["GET","POST","PUT","DELETE","OPTIONS"]
serviceEndpoints:
  agencia:
    url: 'http://localhost:3007'
  reporte:
    url: 'http://localhost:3006'
  usuario:
    url: 'http://localhost:3005'
  httpbin:
    url: 'https://httpbin.org'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  # default:
  #   apiEndpoints:
  #     - api
  #   policies:
  #   # Uncomment `key-auth:` when instructed to in the Getting Started guide.
  #   # - key-auth:
  #     - proxy:
  #         - action:
  #             serviceEndpoint: httpbin 
  #             changeOrigin: true
  agencia:
    apiEndpoints:
      - agencia
      - serviceType
      - serviceAgency
    policies:
      - cors:
        - action:
            origin: '*'
            credentials: true
            methods: GET,POST,PUT,DELETE,OPTIONS
            allowedHeaders: ['Content-type','Authorization','Origin','Access-Control-Allow-Origin','Accept','Options']
            exposedHeaders: ['Content-type','Authorization','Origin','Access-Control-Allow-Origin','Accept','Options']
            #exposedHeaders : ['Content-type','Authorization','Origin','Access-Control-Allow-Origin','Origin', 'Accept', 'X-Requested-With', 'Content-Type', 'Access-Control-Request-Method', 'Access-Control-Request-Headers','Authorization', 'Access-Control-Allow-Origin','X-TEST']
            preflightContinue: true
            optionsSuccessStatus: 204
      - rate-limit:
        - action:
            max: 10
            windowMs: 1000
      - proxy:
          - action:
              serviceEndpoint: agencia
              changeOrigin: true
  usuario:
    apiEndpoints:
      - users
      - ingresar
    policies:
      - cors:
        - action:
            origin: '*'
            methods: GET,POST,PUT,DELETE,OPTIONS
            credentials: true
            allowedHeaders: ['Content-type','Authorization','Origin','Access-Control-Allow-Origin','Accept','Options']
            exposedHeaders: ['Content-type','Authorization','Origin','Access-Control-Allow-Origin','Accept','Options']
            #exposedHeaders : ['Content-type','Authorization','Origin','Access-Control-Allow-Origin','Origin', 'Accept', 'X-Requested-With', 'Content-Type', 'Access-Control-Request-Method', 'Access-Control-Request-Headers','Authorization', 'Access-Control-Allow-Origin','X-TEST']
            preflightContinue: true
            optionsSuccessStatus: 204
      - rate-limit:
        - action:
            max: 10
            windowMs: 1000
      - proxy:
          - action:
              serviceEndpoint: usuario
              changeOrigin: true
  reporte:
    apiEndpoints:
      - reporte
    policies:
      - cors:
        - action:
            origin: '*'
            credentials: true
            methods: GET,POST,PUT,DELETE,OPTIONS
            allowedHeaders: ['Content-type','Authorization','Origin','Access-Control-Allow-Origin','Accept','Options']
            exposedHeaders: ['Content-type','Authorization','Origin','Access-Control-Allow-Origin','Accept','Options']
            #exposedHeaders : ['Content-type','Authorization','Origin','Access-Control-Allow-Origin','Origin', 'Accept', 'X-Requested-With', 'Content-Type', 'Access-Control-Request-Method', 'Access-Control-Request-Headers','Authorization', 'Access-Control-Allow-Origin','X-TEST']
            preflightContinue: true
            optionsSuccessStatus: 204
      - rate-limit:
        - action:
            max: 10
            windowMs: 1000
      - proxy:
          - action:
              serviceEndpoint: reporte
              changeOrigin: true
